name: Build .NET Lambda Container

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/StockPicker.Lambda

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o ./bin/Release/net8.0/publish -p:PublishReadyToRun=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-publish
          path: src/StockPicker.Lambda/bin/Release/net8.0/publish